### ISSUE TITLE
File extension case causes script to stop early

### ISSUE THREAD

**Issue by aammd** [mikeyEcology/MLWIC_examples#1]
Hello @mikeyEcology et al.! This is a wonderful example: it's well documented and very easy to learn from. 
When I ran it on my machine, I found one small hiccup. All the photos from `CA-01_0006971` onwards have a capitalized extension (JPG) rather than a lowercase one. This caused the example to stop partway through for me: `No such file or directory`

**Comment by dwwolfson** [comment]
@aammd , thanks for the comment. I think the script I've been using to resize images has been causing this issue with the file extensions. I'll change all the extensions to lower-case in the repo.

**Comment by dwwolfson** [comment]
Should be resolved now.
