### ISSUE TITLE
Output file not found

### ISSUE THREAD

**Issue by nithya255** [mikeyEcology/MLWIC_examples#3]
We have been trying this package,the installation is proceed according to your manual. We started with your example images, the classify function worked where it have created the output file in the mentioned place but the output file is not found in the respective place nor the make_output found the file. So please help in sorting the issue as soon as possible.

**Comment by mikeyEcology** [comment]
Can you provide your input code and the output that you received in R?

**Comment by nithya255** [comment]
[result.docx](https://github.com/mikeyEcology/MLWIC_examples/files/2988105/result.docx)
I have attached the file. Let me know if you can view the file?

**Comment by nithya255** [comment]
I have followed each and every step you have mentioned in your manual.
1) by installing Anaconda3
2) Installed Tensor flow from Anaconda Navigator
3) Downloaded L1 Folder
4) Downloaded MLWIC package in R
5) Setup environment was ran using the following code
setup(python_loc = "C:/Users/Samruddhi/AppData/Local/Continuum/anaconda3/")
after running the above code the following error was obtained
Use "conda search <package> --info" to see the dependencies for each package.
# Error: Error 1 occurred installing packages into conda environment r-reticulate
Then for testing the model, as you have mentioned I have used your examples to view the output, So i ran the classify code
# classify(
   # path_prefix = "D:/A/images",  
    #data_info = "D:/A/L1/data_info.csv", 
    #model_dir = "D:/A", 
   # python_loc = "C:/Users/Samuriddhi/AppData/Local/Continuum/anaconda3/", # remember to include the last slash
   # save_predictions = "model_predictions.txt" 
# )
The output of the code was the " Evaluation of the images took 0.000993967056274414 secs. The results are stored  in D:/A/L1/model_predictions.In a "viewer friendly format, please use make_output function"
Then the make_output function is used 
#make_output(
    #output_location = "D:/A", 
    #output_name = "output.csv", 
    #model_dir = "D:/A", 
   # saved_predictions = "model_predictions.txt"
# )
The error obtained here was "Error in file(file,"rt"): cannot open the connection"
Please do the need

**Comment by mikeyEcology** [comment]
Windows seems to cause issues when trying to pull images from a hard drive. I think that some other Windows users have found ways around this. It's worth checking out [this Windows user guide](https://github.com/mikeyEcology/MLWIC_examples/blob/master/MLWIC_Windows_Set_up.md) that was provided by @Nova-Scotia .
